package com.tms.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.Map;
//import javax.persistence.*;

@Data
@DynamoDBDocument
//@DynamoDBTable(tableName = "tariff")
public class Tariff {

//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    private String id;

    @DynamoDBAttribute
//    @ElementCollection
    private Map<String, Integer> tariffList;

    public Tariff(Map<String, Integer> tariffList) {
        this.tariffList = tariffList;
    }

    public Tariff() {}
}
